apiVersion: v2
name: pedido-app
description: A Helm chart for managing orders
version: 0.1.0
dependencies:
  - name: postgresql
    version: <versiÃ³n>
    repository: https://charts.bitnami.com/bitnami 